#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DermalogMultiScannerDemo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="informetriQ")]
	public partial class tranxDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertfingerprint_Table_verify(fingerprint_Table_verify instance);
    partial void Updatefingerprint_Table_verify(fingerprint_Table_verify instance);
    partial void Deletefingerprint_Table_verify(fingerprint_Table_verify instance);
    partial void Insertfingerprint_Table(fingerprint_Table instance);
    partial void Updatefingerprint_Table(fingerprint_Table instance);
    partial void Deletefingerprint_Table(fingerprint_Table instance);
    partial void InsertuserTable_1(userTable_1 instance);
    partial void UpdateuserTable_1(userTable_1 instance);
    partial void DeleteuserTable_1(userTable_1 instance);
    partial void Insertindividual_data(individual_data instance);
    partial void Updateindividual_data(individual_data instance);
    partial void Deleteindividual_data(individual_data instance);
    partial void InsertappControlTable_1(appControlTable_1 instance);
    partial void UpdateappControlTable_1(appControlTable_1 instance);
    partial void DeleteappControlTable_1(appControlTable_1 instance);
    #endregion
		
		public tranxDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public tranxDataContext() :
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["informetriQConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}

		public tranxDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tranxDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public tranxDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<fingerprint_Table_verify> fingerprint_Table_verifies
		{
			get
			{
				return this.GetTable<fingerprint_Table_verify>();
			}
		}
		
		public System.Data.Linq.Table<fingerprint_Table> fingerprint_Tables
		{
			get
			{
				return this.GetTable<fingerprint_Table>();
			}
		}
		
		public System.Data.Linq.Table<userTable_1> userTable_1s
		{
			get
			{
				return this.GetTable<userTable_1>();
			}
		}
		
		public System.Data.Linq.Table<individual_data> individual_datas
		{
			get
			{
				return this.GetTable<individual_data>();
			}
		}
		
		public System.Data.Linq.Table<appControlTable_1> appControlTable_1s
		{
			get
			{
				return this.GetTable<appControlTable_1>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.gen_next_req")]
		public int gen_next_req([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(25)")] ref string out_new_req)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), out_new_req);
			out_new_req = ((string)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fingerprint_Table_verify")]
	public partial class fingerprint_Table_verify : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _refNO;
		
		private string _templateString;
		
		private string _templatePath;
		
		private string _position;
		
		private string _finger_data;
		
		private string _identifiedAS;
		
		private string _VerifiedAS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrefNOChanging(string value);
    partial void OnrefNOChanged();
    partial void OntemplateStringChanging(string value);
    partial void OntemplateStringChanged();
    partial void OntemplatePathChanging(string value);
    partial void OntemplatePathChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void Onfinger_dataChanging(string value);
    partial void Onfinger_dataChanged();
    partial void OnidentifiedASChanging(string value);
    partial void OnidentifiedASChanged();
    partial void OnVerifiedASChanging(string value);
    partial void OnVerifiedASChanged();
    #endregion
		
		public fingerprint_Table_verify()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refNO", DbType="VarChar(50)", IsPrimaryKey=true)]
		public string refNO
		{
			get
			{
				return this._refNO;
			}
			set
			{
				if ((this._refNO != value))
				{
					this.OnrefNOChanging(value);
					this.SendPropertyChanging();
					this._refNO = value;
					this.SendPropertyChanged("refNO");
					this.OnrefNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_templateString", DbType="VarChar(50)", IsPrimaryKey=true)]
		public string templateString
		{
			get
			{
				return this._templateString;
			}
			set
			{
				if ((this._templateString != value))
				{
					this.OntemplateStringChanging(value);
					this.SendPropertyChanging();
					this._templateString = value;
					this.SendPropertyChanged("templateString");
					this.OntemplateStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_templatePath", DbType="VarChar(MAX)")]
		public string templatePath
		{
			get
			{
				return this._templatePath;
			}
			set
			{
				if ((this._templatePath != value))
				{
					this.OntemplatePathChanging(value);
					this.SendPropertyChanging();
					this._templatePath = value;
					this.SendPropertyChanged("templatePath");
					this.OntemplatePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(5)")]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finger_data", DbType="NVarChar(MAX)")]
		public string finger_data
		{
			get
			{
				return this._finger_data;
			}
			set
			{
				if ((this._finger_data != value))
				{
					this.Onfinger_dataChanging(value);
					this.SendPropertyChanging();
					this._finger_data = value;
					this.SendPropertyChanged("finger_data");
					this.Onfinger_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_identifiedAS", DbType="VarChar(50)")]
		public string identifiedAS
		{
			get
			{
				return this._identifiedAS;
			}
			set
			{
				if ((this._identifiedAS != value))
				{
					this.OnidentifiedASChanging(value);
					this.SendPropertyChanging();
					this._identifiedAS = value;
					this.SendPropertyChanged("identifiedAS");
					this.OnidentifiedASChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VerifiedAS", DbType="VarChar(50)")]
		public string VerifiedAS
		{
			get
			{
				return this._VerifiedAS;
			}
			set
			{
				if ((this._VerifiedAS != value))
				{
					this.OnVerifiedASChanging(value);
					this.SendPropertyChanging();
					this._VerifiedAS = value;
					this.SendPropertyChanged("VerifiedAS");
					this.OnVerifiedASChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.fingerprint_Table")]
	public partial class fingerprint_Table : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _refNO;
		
		private string _templateString;
		
		private string _templatePath;
		
		private string _position;
		
		private string _finger_data;
		
		private string _hand_spec;
		
		private string _hand_position;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrefNOChanging(string value);
    partial void OnrefNOChanged();
    partial void OntemplateStringChanging(string value);
    partial void OntemplateStringChanged();
    partial void OntemplatePathChanging(string value);
    partial void OntemplatePathChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void Onfinger_dataChanging(string value);
    partial void Onfinger_dataChanged();
    partial void Onhand_specChanging(string value);
    partial void Onhand_specChanged();
    partial void Onhand_positionChanging(string value);
    partial void Onhand_positionChanged();
    #endregion
		
		public fingerprint_Table()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_refNO", DbType="VarChar(50)", IsPrimaryKey=true)]
		public string refNO
		{
			get
			{
				return this._refNO;
			}
			set
			{
				if ((this._refNO != value))
				{
					this.OnrefNOChanging(value);
					this.SendPropertyChanging();
					this._refNO = value;
					this.SendPropertyChanged("refNO");
					this.OnrefNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_templateString", DbType="VarChar(50)")]
		public string templateString
		{
			get
			{
				return this._templateString;
			}
			set
			{
				if ((this._templateString != value))
				{
					this.OntemplateStringChanging(value);
					this.SendPropertyChanging();
					this._templateString = value;
					this.SendPropertyChanged("templateString");
					this.OntemplateStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_templatePath", DbType="VarChar(MAX)")]
		public string templatePath
		{
			get
			{
				return this._templatePath;
			}
			set
			{
				if ((this._templatePath != value))
				{
					this.OntemplatePathChanging(value);
					this.SendPropertyChanging();
					this._templatePath = value;
					this.SendPropertyChanged("templatePath");
					this.OntemplatePathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(5)", IsPrimaryKey=true)]
		public string position
		{
			get
			{
				return this._position;
			}
			set
			{
				if ((this._position != value))
				{
					this.OnpositionChanging(value);
					this.SendPropertyChanging();
					this._position = value;
					this.SendPropertyChanged("position");
					this.OnpositionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finger_data", DbType="NVarChar(MAX)")]
		public string finger_data
		{
			get
			{
				return this._finger_data;
			}
			set
			{
				if ((this._finger_data != value))
				{
					this.Onfinger_dataChanging(value);
					this.SendPropertyChanging();
					this._finger_data = value;
					this.SendPropertyChanged("finger_data");
					this.Onfinger_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hand_spec", DbType="VarChar(10)")]
		public string hand_spec
		{
			get
			{
				return this._hand_spec;
			}
			set
			{
				if ((this._hand_spec != value))
				{
					this.Onhand_specChanging(value);
					this.SendPropertyChanging();
					this._hand_spec = value;
					this.SendPropertyChanged("hand_spec");
					this.Onhand_specChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hand_position", DbType="VarChar(5)")]
		public string hand_position
		{
			get
			{
				return this._hand_position;
			}
			set
			{
				if ((this._hand_position != value))
				{
					this.Onhand_positionChanging(value);
					this.SendPropertyChanging();
					this._hand_position = value;
					this.SendPropertyChanged("hand_position");
					this.Onhand_positionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.userTable_1")]
	public partial class userTable_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _idString;
		
		private string _username;
		
		private string _idPath;
		
		private string _userPath;
		
		private string _live_image;
		
		private System.Nullable<long> _id;
		
		private string _finger_Enrolled;
		
		private string _finger_remark;
		
		private string _createdby;
		
		private System.Nullable<System.DateTime> _LastActivityDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidStringChanging(string value);
    partial void OnidStringChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnidPathChanging(string value);
    partial void OnidPathChanged();
    partial void OnuserPathChanging(string value);
    partial void OnuserPathChanged();
    partial void Onlive_imageChanging(string value);
    partial void Onlive_imageChanged();
    partial void OnidChanging(System.Nullable<long> value);
    partial void OnidChanged();
    partial void Onfinger_EnrolledChanging(string value);
    partial void Onfinger_EnrolledChanged();
    partial void Onfinger_remarkChanging(string value);
    partial void Onfinger_remarkChanged();
    partial void OncreatedbyChanging(string value);
    partial void OncreatedbyChanged();
    partial void OnLastActivityDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastActivityDateChanged();
    #endregion
		
		public userTable_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idString", DbType="VarChar(50)")]
		public string idString
		{
			get
			{
				return this._idString;
			}
			set
			{
				if ((this._idString != value))
				{
					this.OnidStringChanging(value);
					this.SendPropertyChanging();
					this._idString = value;
					this.SendPropertyChanged("idString");
					this.OnidStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPath", DbType="VarChar(MAX)")]
		public string idPath
		{
			get
			{
				return this._idPath;
			}
			set
			{
				if ((this._idPath != value))
				{
					this.OnidPathChanging(value);
					this.SendPropertyChanging();
					this._idPath = value;
					this.SendPropertyChanged("idPath");
					this.OnidPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userPath", DbType="VarChar(10)")]
		public string userPath
		{
			get
			{
				return this._userPath;
			}
			set
			{
				if ((this._userPath != value))
				{
					this.OnuserPathChanging(value);
					this.SendPropertyChanging();
					this._userPath = value;
					this.SendPropertyChanged("userPath");
					this.OnuserPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_live_image", DbType="NVarChar(MAX)")]
		public string live_image
		{
			get
			{
				return this._live_image;
			}
			set
			{
				if ((this._live_image != value))
				{
					this.Onlive_imageChanging(value);
					this.SendPropertyChanging();
					this._live_image = value;
					this.SendPropertyChanged("live_image");
					this.Onlive_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="BigInt", IsPrimaryKey=true)]
		public System.Nullable<long> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finger_Enrolled", DbType="VarChar(2)")]
		public string finger_Enrolled
		{
			get
			{
				return this._finger_Enrolled;
			}
			set
			{
				if ((this._finger_Enrolled != value))
				{
					this.Onfinger_EnrolledChanging(value);
					this.SendPropertyChanging();
					this._finger_Enrolled = value;
					this.SendPropertyChanged("finger_Enrolled");
					this.Onfinger_EnrolledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finger_remark", DbType="VarChar(MAX)")]
		public string finger_remark
		{
			get
			{
				return this._finger_remark;
			}
			set
			{
				if ((this._finger_remark != value))
				{
					this.Onfinger_remarkChanging(value);
					this.SendPropertyChanging();
					this._finger_remark = value;
					this.SendPropertyChanged("finger_remark");
					this.Onfinger_remarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdby", DbType="VarChar(150)")]
		public string createdby
		{
			get
			{
				return this._createdby;
			}
			set
			{
				if ((this._createdby != value))
				{
					this.OncreatedbyChanging(value);
					this.SendPropertyChanging();
					this._createdby = value;
					this.SendPropertyChanged("createdby");
					this.OncreatedbyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastActivityDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastActivityDate
		{
			get
			{
				return this._LastActivityDate;
			}
			set
			{
				if ((this._LastActivityDate != value))
				{
					this.OnLastActivityDateChanging(value);
					this.SendPropertyChanging();
					this._LastActivityDate = value;
					this.SendPropertyChanged("LastActivityDate");
					this.OnLastActivityDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.individual_data")]
	public partial class individual_data : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _first_name;
		
		private string _last_name;
		
		private string _username;
		
		private string _email;
		
		private string _dob;
		
		private string _state;
		
		private string _country;
		
		private string _profession;
		
		private string _about;
		
		private string _phone;
		
		private string _website;
		
		private string _gender;
		
		private string _confirmation_code;
		
		private string _social_facebook;
		
		private string _social_twitter;
		
		private string _social_instagram;
		
		private string _social_linkedin;
		
		private string _social_youtube;
		
		private string _politics;
		
		private string _recognition;
		
		private string _hide_dob;
		
		private string _rating;
		
		private string _status;
		
		private string _verified_status;
		
		private string _created_on;
		
		private string _last_updated_on;
		
		private string _state_name;
		
		private string _profession_name;
		
		private string _strResponse;
		
		private string _account_type;
		
		private string _enrolled;
		
		private string _web_feedback;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onlast_nameChanging(string value);
    partial void Onlast_nameChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OndobChanging(string value);
    partial void OndobChanged();
    partial void OnstateChanging(string value);
    partial void OnstateChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OnprofessionChanging(string value);
    partial void OnprofessionChanged();
    partial void OnaboutChanging(string value);
    partial void OnaboutChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnwebsiteChanging(string value);
    partial void OnwebsiteChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void Onconfirmation_codeChanging(string value);
    partial void Onconfirmation_codeChanged();
    partial void Onsocial_facebookChanging(string value);
    partial void Onsocial_facebookChanged();
    partial void Onsocial_twitterChanging(string value);
    partial void Onsocial_twitterChanged();
    partial void Onsocial_instagramChanging(string value);
    partial void Onsocial_instagramChanged();
    partial void Onsocial_linkedinChanging(string value);
    partial void Onsocial_linkedinChanged();
    partial void Onsocial_youtubeChanging(string value);
    partial void Onsocial_youtubeChanged();
    partial void OnpoliticsChanging(string value);
    partial void OnpoliticsChanged();
    partial void OnrecognitionChanging(string value);
    partial void OnrecognitionChanged();
    partial void Onhide_dobChanging(string value);
    partial void Onhide_dobChanged();
    partial void OnratingChanging(string value);
    partial void OnratingChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Onverified_statusChanging(string value);
    partial void Onverified_statusChanged();
    partial void Oncreated_onChanging(string value);
    partial void Oncreated_onChanged();
    partial void Onlast_updated_onChanging(string value);
    partial void Onlast_updated_onChanged();
    partial void Onstate_nameChanging(string value);
    partial void Onstate_nameChanged();
    partial void Onprofession_nameChanging(string value);
    partial void Onprofession_nameChanged();
    partial void OnstrResponseChanging(string value);
    partial void OnstrResponseChanged();
    partial void Onaccount_typeChanging(string value);
    partial void Onaccount_typeChanged();
    partial void OnenrolledChanging(string value);
    partial void OnenrolledChanged();
    partial void Onweb_feedbackChanging(string value);
    partial void Onweb_feedbackChanged();
    #endregion
		
		public individual_data()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(10)")]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="VarChar(50)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="VarChar(50)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this.Onlast_nameChanging(value);
					this.SendPropertyChanging();
					this._last_name = value;
					this.SendPropertyChanged("last_name");
					this.Onlast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(100)", IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="VarChar(100)")]
		public string dob
		{
			get
			{
				return this._dob;
			}
			set
			{
				if ((this._dob != value))
				{
					this.OndobChanging(value);
					this.SendPropertyChanging();
					this._dob = value;
					this.SendPropertyChanged("dob");
					this.OndobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(100)")]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this.OnstateChanging(value);
					this.SendPropertyChanging();
					this._state = value;
					this.SendPropertyChanged("state");
					this.OnstateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(100)")]
		public string country
		{
			get
			{
				return this._country;
			}
			set
			{
				if ((this._country != value))
				{
					this.OncountryChanging(value);
					this.SendPropertyChanging();
					this._country = value;
					this.SendPropertyChanged("country");
					this.OncountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profession", DbType="VarChar(100)")]
		public string profession
		{
			get
			{
				return this._profession;
			}
			set
			{
				if ((this._profession != value))
				{
					this.OnprofessionChanging(value);
					this.SendPropertyChanging();
					this._profession = value;
					this.SendPropertyChanged("profession");
					this.OnprofessionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_about", DbType="VarChar(MAX)")]
		public string about
		{
			get
			{
				return this._about;
			}
			set
			{
				if ((this._about != value))
				{
					this.OnaboutChanging(value);
					this.SendPropertyChanging();
					this._about = value;
					this.SendPropertyChanged("about");
					this.OnaboutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(100)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="VarChar(100)")]
		public string website
		{
			get
			{
				return this._website;
			}
			set
			{
				if ((this._website != value))
				{
					this.OnwebsiteChanging(value);
					this.SendPropertyChanging();
					this._website = value;
					this.SendPropertyChanged("website");
					this.OnwebsiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="VarChar(100)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_confirmation_code", DbType="VarChar(100)")]
		public string confirmation_code
		{
			get
			{
				return this._confirmation_code;
			}
			set
			{
				if ((this._confirmation_code != value))
				{
					this.Onconfirmation_codeChanging(value);
					this.SendPropertyChanging();
					this._confirmation_code = value;
					this.SendPropertyChanged("confirmation_code");
					this.Onconfirmation_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_social_facebook", DbType="VarChar(100)")]
		public string social_facebook
		{
			get
			{
				return this._social_facebook;
			}
			set
			{
				if ((this._social_facebook != value))
				{
					this.Onsocial_facebookChanging(value);
					this.SendPropertyChanging();
					this._social_facebook = value;
					this.SendPropertyChanged("social_facebook");
					this.Onsocial_facebookChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_social_twitter", DbType="VarChar(100)")]
		public string social_twitter
		{
			get
			{
				return this._social_twitter;
			}
			set
			{
				if ((this._social_twitter != value))
				{
					this.Onsocial_twitterChanging(value);
					this.SendPropertyChanging();
					this._social_twitter = value;
					this.SendPropertyChanged("social_twitter");
					this.Onsocial_twitterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_social_instagram", DbType="VarChar(100)")]
		public string social_instagram
		{
			get
			{
				return this._social_instagram;
			}
			set
			{
				if ((this._social_instagram != value))
				{
					this.Onsocial_instagramChanging(value);
					this.SendPropertyChanging();
					this._social_instagram = value;
					this.SendPropertyChanged("social_instagram");
					this.Onsocial_instagramChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_social_linkedin", DbType="VarChar(100)")]
		public string social_linkedin
		{
			get
			{
				return this._social_linkedin;
			}
			set
			{
				if ((this._social_linkedin != value))
				{
					this.Onsocial_linkedinChanging(value);
					this.SendPropertyChanging();
					this._social_linkedin = value;
					this.SendPropertyChanged("social_linkedin");
					this.Onsocial_linkedinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_social_youtube", DbType="VarChar(100)")]
		public string social_youtube
		{
			get
			{
				return this._social_youtube;
			}
			set
			{
				if ((this._social_youtube != value))
				{
					this.Onsocial_youtubeChanging(value);
					this.SendPropertyChanging();
					this._social_youtube = value;
					this.SendPropertyChanged("social_youtube");
					this.Onsocial_youtubeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_politics", DbType="VarChar(100)")]
		public string politics
		{
			get
			{
				return this._politics;
			}
			set
			{
				if ((this._politics != value))
				{
					this.OnpoliticsChanging(value);
					this.SendPropertyChanging();
					this._politics = value;
					this.SendPropertyChanged("politics");
					this.OnpoliticsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recognition", DbType="VarChar(MAX)")]
		public string recognition
		{
			get
			{
				return this._recognition;
			}
			set
			{
				if ((this._recognition != value))
				{
					this.OnrecognitionChanging(value);
					this.SendPropertyChanging();
					this._recognition = value;
					this.SendPropertyChanged("recognition");
					this.OnrecognitionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hide_dob", DbType="VarChar(100)")]
		public string hide_dob
		{
			get
			{
				return this._hide_dob;
			}
			set
			{
				if ((this._hide_dob != value))
				{
					this.Onhide_dobChanging(value);
					this.SendPropertyChanging();
					this._hide_dob = value;
					this.SendPropertyChanged("hide_dob");
					this.Onhide_dobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rating", DbType="VarChar(100)")]
		public string rating
		{
			get
			{
				return this._rating;
			}
			set
			{
				if ((this._rating != value))
				{
					this.OnratingChanging(value);
					this.SendPropertyChanging();
					this._rating = value;
					this.SendPropertyChanged("rating");
					this.OnratingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(100)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_verified_status", DbType="VarChar(100)")]
		public string verified_status
		{
			get
			{
				return this._verified_status;
			}
			set
			{
				if ((this._verified_status != value))
				{
					this.Onverified_statusChanging(value);
					this.SendPropertyChanging();
					this._verified_status = value;
					this.SendPropertyChanged("verified_status");
					this.Onverified_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_on", DbType="VarChar(100)")]
		public string created_on
		{
			get
			{
				return this._created_on;
			}
			set
			{
				if ((this._created_on != value))
				{
					this.Oncreated_onChanging(value);
					this.SendPropertyChanging();
					this._created_on = value;
					this.SendPropertyChanged("created_on");
					this.Oncreated_onChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_updated_on", DbType="VarChar(100)")]
		public string last_updated_on
		{
			get
			{
				return this._last_updated_on;
			}
			set
			{
				if ((this._last_updated_on != value))
				{
					this.Onlast_updated_onChanging(value);
					this.SendPropertyChanging();
					this._last_updated_on = value;
					this.SendPropertyChanged("last_updated_on");
					this.Onlast_updated_onChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_name", DbType="VarChar(100)")]
		public string state_name
		{
			get
			{
				return this._state_name;
			}
			set
			{
				if ((this._state_name != value))
				{
					this.Onstate_nameChanging(value);
					this.SendPropertyChanging();
					this._state_name = value;
					this.SendPropertyChanged("state_name");
					this.Onstate_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_profession_name", DbType="VarChar(100)")]
		public string profession_name
		{
			get
			{
				return this._profession_name;
			}
			set
			{
				if ((this._profession_name != value))
				{
					this.Onprofession_nameChanging(value);
					this.SendPropertyChanging();
					this._profession_name = value;
					this.SendPropertyChanged("profession_name");
					this.Onprofession_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strResponse", DbType="VarChar(MAX)")]
		public string strResponse
		{
			get
			{
				return this._strResponse;
			}
			set
			{
				if ((this._strResponse != value))
				{
					this.OnstrResponseChanging(value);
					this.SendPropertyChanging();
					this._strResponse = value;
					this.SendPropertyChanged("strResponse");
					this.OnstrResponseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_account_type", DbType="VarChar(20)")]
		public string account_type
		{
			get
			{
				return this._account_type;
			}
			set
			{
				if ((this._account_type != value))
				{
					this.Onaccount_typeChanging(value);
					this.SendPropertyChanging();
					this._account_type = value;
					this.SendPropertyChanged("account_type");
					this.Onaccount_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enrolled", DbType="VarChar(20)")]
		public string enrolled
		{
			get
			{
				return this._enrolled;
			}
			set
			{
				if ((this._enrolled != value))
				{
					this.OnenrolledChanging(value);
					this.SendPropertyChanging();
					this._enrolled = value;
					this.SendPropertyChanged("enrolled");
					this.OnenrolledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web_feedback", DbType="VarChar(20)")]
		public string web_feedback
		{
			get
			{
				return this._web_feedback;
			}
			set
			{
				if ((this._web_feedback != value))
				{
					this.Onweb_feedbackChanging(value);
					this.SendPropertyChanging();
					this._web_feedback = value;
					this.SendPropertyChanged("web_feedback");
					this.Onweb_feedbackChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.appControlTable_1")]
	public partial class appControlTable_1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _paramName;
		
		private string _paramValue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnparamNameChanging(string value);
    partial void OnparamNameChanged();
    partial void OnparamValueChanging(string value);
    partial void OnparamValueChanged();
    #endregion
		
		public appControlTable_1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paramName", DbType="VarChar(150)", IsPrimaryKey=true)]
		public string paramName
		{
			get
			{
				return this._paramName;
			}
			set
			{
				if ((this._paramName != value))
				{
					this.OnparamNameChanging(value);
					this.SendPropertyChanging();
					this._paramName = value;
					this.SendPropertyChanged("paramName");
					this.OnparamNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paramValue", DbType="VarChar(MAX)")]
		public string paramValue
		{
			get
			{
				return this._paramValue;
			}
			set
			{
				if ((this._paramValue != value))
				{
					this.OnparamValueChanging(value);
					this.SendPropertyChanging();
					this._paramValue = value;
					this.SendPropertyChanged("paramValue");
					this.OnparamValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
