//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8800
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DermalogMultiScannerDemo.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://192.168.40.253:81/", ConfigurationName="ServiceReference1.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/HelloWorld2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string HelloWorld2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/get_JSON", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string get_JSON(DermalogMultiScannerDemo.ServiceReference1.sample_response mm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/getList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/getList2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string[] getList2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/getListAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getListAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/getListTaxmaster", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getListTaxmaster(string cmdSQL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/getListAnySQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getListAnySQL(string cmdSQL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/genReportAnySQL", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string genReportAnySQL(string cmdSQL, string sfilename, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/getListAnySQLTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        System.Data.DataTable getListAnySQLTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/send_getList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string send_getList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/send_getList_new", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        string send_getList_new();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.8773")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://192.168.40.253:81/")]
    public partial class sample_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bVNField;
        
        private string responseCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BVN {
            get {
                return this.bVNField;
            }
            set {
                this.bVNField = value;
                this.RaisePropertyChanged("BVN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResponseCode {
            get {
                return this.responseCodeField;
            }
            set {
                this.responseCodeField = value;
                this.RaisePropertyChanged("ResponseCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceSoapChannel : DermalogMultiScannerDemo.ServiceReference1.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<DermalogMultiScannerDemo.ServiceReference1.ServiceSoap>, DermalogMultiScannerDemo.ServiceReference1.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public string HelloWorld2() {
            return base.Channel.HelloWorld2();
        }
        
        public string get_JSON(DermalogMultiScannerDemo.ServiceReference1.sample_response mm) {
            return base.Channel.get_JSON(mm);
        }
        
        public string[] getList() {
            return base.Channel.getList();
        }
        
        public string[] getList2() {
            return base.Channel.getList2();
        }
        
        public System.Data.DataTable getListAll() {
            return base.Channel.getListAll();
        }
        
        public System.Data.DataTable getListTaxmaster(string cmdSQL) {
            return base.Channel.getListTaxmaster(cmdSQL);
        }
        
        public System.Data.DataTable getListAnySQL(string cmdSQL) {
            return base.Channel.getListAnySQL(cmdSQL);
        }
        
        public string genReportAnySQL(string cmdSQL, string sfilename, string username) {
            return base.Channel.genReportAnySQL(cmdSQL, sfilename, username);
        }
        
        public System.Data.DataTable getListAnySQLTest() {
            return base.Channel.getListAnySQLTest();
        }
        
        public string send_getList() {
            return base.Channel.send_getList();
        }
        
        public string send_getList_new() {
            return base.Channel.send_getList_new();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://192.168.40.253:81/", ConfigurationName="ServiceReference1.ServiceHttpGet")]
    public interface ServiceHttpGet {
        
        // CODEGEN: Generating message contract since the operation HelloWorld is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpGet/HelloWorldRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpGet/HelloWorldResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.HelloWorldResponse HelloWorld(DermalogMultiScannerDemo.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since the operation HelloWorld2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpGet/HelloWorld2Request", ReplyAction="http://192.168.40.253:81/ServiceHttpGet/HelloWorld2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Response HelloWorld2(DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Request request);
        
        // CODEGEN: Generating message contract since the operation getList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpGet/getListRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpGet/getListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getListResponse getList(DermalogMultiScannerDemo.ServiceReference1.getListRequest request);
        
        // CODEGEN: Generating message contract since the operation getList2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpGet/getList2Request", ReplyAction="http://192.168.40.253:81/ServiceHttpGet/getList2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getList2Response getList2(DermalogMultiScannerDemo.ServiceReference1.getList2Request request);
        
        // CODEGEN: Generating message contract since the operation getListAll is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpGet/getListAllRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpGet/getListAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getListAllResponse getListAll(DermalogMultiScannerDemo.ServiceReference1.getListAllRequest request);
        
        // CODEGEN: Generating message contract since the operation getListTaxmaster is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpGet/getListTaxmasterRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpGet/getListTaxmasterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterResponse getListTaxmaster(DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterRequest request);
        
        // CODEGEN: Generating message contract since the operation getListAnySQL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpGet/getListAnySQLRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpGet/getListAnySQLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getListAnySQLResponse getListAnySQL(DermalogMultiScannerDemo.ServiceReference1.getListAnySQLRequest request);
        
        // CODEGEN: Generating message contract since the operation genReportAnySQL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpGet/genReportAnySQLRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpGet/genReportAnySQLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLResponse genReportAnySQL(DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLRequest request);
        
        // CODEGEN: Generating message contract since the operation getListAnySQLTest is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpGet/getListAnySQLTestRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpGet/getListAnySQLTestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestResponse getListAnySQLTest(DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestRequest request);
        
        // CODEGEN: Generating message contract since the operation send_getList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpGet/send_getListRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpGet/send_getListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.send_getListResponse send_getList(DermalogMultiScannerDemo.ServiceReference1.send_getListRequest request);
        
        // CODEGEN: Generating message contract since the operation send_getList_new is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpGet/send_getList_newRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpGet/send_getList_newResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.send_getList_newResponse send_getList_new(DermalogMultiScannerDemo.ServiceReference1.send_getList_newRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        public HelloWorldRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Request {
        
        public HelloWorld2Request() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public HelloWorld2Response() {
        }
        
        public HelloWorld2Response(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListRequest {
        
        public getListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getListResponse() {
        }
        
        public getListResponse(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getList2Request {
        
        public getList2Request() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getList2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getList2Response() {
        }
        
        public getList2Response(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAllRequest {
        
        public getListAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable DataTable;
        
        public getListAllResponse() {
        }
        
        public getListAllResponse(System.Data.DataTable DataTable) {
            this.DataTable = DataTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListTaxmasterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cmdSQL;
        
        public getListTaxmasterRequest() {
        }
        
        public getListTaxmasterRequest(string cmdSQL) {
            this.cmdSQL = cmdSQL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListTaxmasterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable DataTable;
        
        public getListTaxmasterResponse() {
        }
        
        public getListTaxmasterResponse(System.Data.DataTable DataTable) {
            this.DataTable = DataTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAnySQLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cmdSQL;
        
        public getListAnySQLRequest() {
        }
        
        public getListAnySQLRequest(string cmdSQL) {
            this.cmdSQL = cmdSQL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAnySQLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable DataTable;
        
        public getListAnySQLResponse() {
        }
        
        public getListAnySQLResponse(System.Data.DataTable DataTable) {
            this.DataTable = DataTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class genReportAnySQLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cmdSQL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string sfilename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string username;
        
        public genReportAnySQLRequest() {
        }
        
        public genReportAnySQLRequest(string cmdSQL, string sfilename, string username) {
            this.cmdSQL = cmdSQL;
            this.sfilename = sfilename;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class genReportAnySQLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public genReportAnySQLResponse() {
        }
        
        public genReportAnySQLResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAnySQLTestRequest {
        
        public getListAnySQLTestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAnySQLTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable DataTable;
        
        public getListAnySQLTestResponse() {
        }
        
        public getListAnySQLTestResponse(System.Data.DataTable DataTable) {
            this.DataTable = DataTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_getListRequest {
        
        public send_getListRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_getListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public send_getListResponse() {
        }
        
        public send_getListResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_getList_newRequest {
        
        public send_getList_newRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_getList_newResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public send_getList_newResponse() {
        }
        
        public send_getList_newResponse(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceHttpGetChannel : DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceHttpGetClient : System.ServiceModel.ClientBase<DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet>, DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet {
        
        public ServiceHttpGetClient() {
        }
        
        public ServiceHttpGetClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHttpGetClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHttpGetClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHttpGetClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.HelloWorldResponse DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet.HelloWorld(DermalogMultiScannerDemo.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DermalogMultiScannerDemo.ServiceReference1.HelloWorldRequest inValue = new DermalogMultiScannerDemo.ServiceReference1.HelloWorldRequest();
            DermalogMultiScannerDemo.ServiceReference1.HelloWorldResponse retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet)(this)).HelloWorld(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Response DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet.HelloWorld2(DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Request request) {
            return base.Channel.HelloWorld2(request);
        }
        
        public string HelloWorld2() {
            DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Request inValue = new DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Request();
            DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Response retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet)(this)).HelloWorld2(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getListResponse DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet.getList(DermalogMultiScannerDemo.ServiceReference1.getListRequest request) {
            return base.Channel.getList(request);
        }
        
        public string[] getList() {
            DermalogMultiScannerDemo.ServiceReference1.getListRequest inValue = new DermalogMultiScannerDemo.ServiceReference1.getListRequest();
            DermalogMultiScannerDemo.ServiceReference1.getListResponse retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet)(this)).getList(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getList2Response DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet.getList2(DermalogMultiScannerDemo.ServiceReference1.getList2Request request) {
            return base.Channel.getList2(request);
        }
        
        public string[] getList2() {
            DermalogMultiScannerDemo.ServiceReference1.getList2Request inValue = new DermalogMultiScannerDemo.ServiceReference1.getList2Request();
            DermalogMultiScannerDemo.ServiceReference1.getList2Response retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet)(this)).getList2(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getListAllResponse DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet.getListAll(DermalogMultiScannerDemo.ServiceReference1.getListAllRequest request) {
            return base.Channel.getListAll(request);
        }
        
        public System.Data.DataTable getListAll() {
            DermalogMultiScannerDemo.ServiceReference1.getListAllRequest inValue = new DermalogMultiScannerDemo.ServiceReference1.getListAllRequest();
            DermalogMultiScannerDemo.ServiceReference1.getListAllResponse retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet)(this)).getListAll(inValue);
            return retVal.DataTable;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterResponse DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet.getListTaxmaster(DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterRequest request) {
            return base.Channel.getListTaxmaster(request);
        }
        
        public System.Data.DataTable getListTaxmaster(string cmdSQL) {
            DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterRequest inValue = new DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterRequest();
            inValue.cmdSQL = cmdSQL;
            DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterResponse retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet)(this)).getListTaxmaster(inValue);
            return retVal.DataTable;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getListAnySQLResponse DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet.getListAnySQL(DermalogMultiScannerDemo.ServiceReference1.getListAnySQLRequest request) {
            return base.Channel.getListAnySQL(request);
        }
        
        public System.Data.DataTable getListAnySQL(string cmdSQL) {
            DermalogMultiScannerDemo.ServiceReference1.getListAnySQLRequest inValue = new DermalogMultiScannerDemo.ServiceReference1.getListAnySQLRequest();
            inValue.cmdSQL = cmdSQL;
            DermalogMultiScannerDemo.ServiceReference1.getListAnySQLResponse retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet)(this)).getListAnySQL(inValue);
            return retVal.DataTable;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLResponse DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet.genReportAnySQL(DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLRequest request) {
            return base.Channel.genReportAnySQL(request);
        }
        
        public string genReportAnySQL(string cmdSQL, string sfilename, string username) {
            DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLRequest inValue = new DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLRequest();
            inValue.cmdSQL = cmdSQL;
            inValue.sfilename = sfilename;
            inValue.username = username;
            DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLResponse retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet)(this)).genReportAnySQL(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestResponse DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet.getListAnySQLTest(DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestRequest request) {
            return base.Channel.getListAnySQLTest(request);
        }
        
        public System.Data.DataTable getListAnySQLTest() {
            DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestRequest inValue = new DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestRequest();
            DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestResponse retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet)(this)).getListAnySQLTest(inValue);
            return retVal.DataTable;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.send_getListResponse DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet.send_getList(DermalogMultiScannerDemo.ServiceReference1.send_getListRequest request) {
            return base.Channel.send_getList(request);
        }
        
        public string send_getList() {
            DermalogMultiScannerDemo.ServiceReference1.send_getListRequest inValue = new DermalogMultiScannerDemo.ServiceReference1.send_getListRequest();
            DermalogMultiScannerDemo.ServiceReference1.send_getListResponse retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet)(this)).send_getList(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.send_getList_newResponse DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet.send_getList_new(DermalogMultiScannerDemo.ServiceReference1.send_getList_newRequest request) {
            return base.Channel.send_getList_new(request);
        }
        
        public string send_getList_new() {
            DermalogMultiScannerDemo.ServiceReference1.send_getList_newRequest inValue = new DermalogMultiScannerDemo.ServiceReference1.send_getList_newRequest();
            DermalogMultiScannerDemo.ServiceReference1.send_getList_newResponse retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpGet)(this)).send_getList_new(inValue);
            return retVal.@string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://192.168.40.253:81/", ConfigurationName="ServiceReference1.ServiceHttpPost")]
    public interface ServiceHttpPost {
        
        // CODEGEN: Generating message contract since the operation HelloWorld is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpPost/HelloWorldRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpPost/HelloWorldResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.HelloWorldResponse1 HelloWorld(DermalogMultiScannerDemo.ServiceReference1.HelloWorldRequest1 request);
        
        // CODEGEN: Generating message contract since the operation HelloWorld2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpPost/HelloWorld2Request", ReplyAction="http://192.168.40.253:81/ServiceHttpPost/HelloWorld2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Response1 HelloWorld2(DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Request1 request);
        
        // CODEGEN: Generating message contract since the operation getList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpPost/getListRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpPost/getListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getListResponse1 getList(DermalogMultiScannerDemo.ServiceReference1.getListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getList2 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpPost/getList2Request", ReplyAction="http://192.168.40.253:81/ServiceHttpPost/getList2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getList2Response1 getList2(DermalogMultiScannerDemo.ServiceReference1.getList2Request1 request);
        
        // CODEGEN: Generating message contract since the operation getListAll is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpPost/getListAllRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpPost/getListAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getListAllResponse1 getListAll(DermalogMultiScannerDemo.ServiceReference1.getListAllRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getListTaxmaster is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpPost/getListTaxmasterRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpPost/getListTaxmasterResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterResponse1 getListTaxmaster(DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getListAnySQL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpPost/getListAnySQLRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpPost/getListAnySQLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getListAnySQLResponse1 getListAnySQL(DermalogMultiScannerDemo.ServiceReference1.getListAnySQLRequest1 request);
        
        // CODEGEN: Generating message contract since the operation genReportAnySQL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpPost/genReportAnySQLRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpPost/genReportAnySQLResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLResponse1 genReportAnySQL(DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLRequest1 request);
        
        // CODEGEN: Generating message contract since the operation getListAnySQLTest is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpPost/getListAnySQLTestRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpPost/getListAnySQLTestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestResponse1 getListAnySQLTest(DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestRequest1 request);
        
        // CODEGEN: Generating message contract since the operation send_getList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpPost/send_getListRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpPost/send_getListResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.send_getListResponse1 send_getList(DermalogMultiScannerDemo.ServiceReference1.send_getListRequest1 request);
        
        // CODEGEN: Generating message contract since the operation send_getList_new is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://192.168.40.253:81/ServiceHttpPost/send_getList_newRequest", ReplyAction="http://192.168.40.253:81/ServiceHttpPost/send_getList_newResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        DermalogMultiScannerDemo.ServiceReference1.send_getList_newResponse1 send_getList_new(DermalogMultiScannerDemo.ServiceReference1.send_getList_newRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest1 {
        
        public HelloWorldRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public HelloWorldResponse1() {
        }
        
        public HelloWorldResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Request1 {
        
        public HelloWorld2Request1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorld2Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public HelloWorld2Response1() {
        }
        
        public HelloWorld2Response1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListRequest1 {
        
        public getListRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getListResponse1() {
        }
        
        public getListResponse1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getList2Request1 {
        
        public getList2Request1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getList2Response1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public string[] ArrayOfString;
        
        public getList2Response1() {
        }
        
        public getList2Response1(string[] ArrayOfString) {
            this.ArrayOfString = ArrayOfString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAllRequest1 {
        
        public getListAllRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAllResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable DataTable;
        
        public getListAllResponse1() {
        }
        
        public getListAllResponse1(System.Data.DataTable DataTable) {
            this.DataTable = DataTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListTaxmasterRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cmdSQL;
        
        public getListTaxmasterRequest1() {
        }
        
        public getListTaxmasterRequest1(string cmdSQL) {
            this.cmdSQL = cmdSQL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListTaxmasterResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable DataTable;
        
        public getListTaxmasterResponse1() {
        }
        
        public getListTaxmasterResponse1(System.Data.DataTable DataTable) {
            this.DataTable = DataTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAnySQLRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cmdSQL;
        
        public getListAnySQLRequest1() {
        }
        
        public getListAnySQLRequest1(string cmdSQL) {
            this.cmdSQL = cmdSQL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAnySQLResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable DataTable;
        
        public getListAnySQLResponse1() {
        }
        
        public getListAnySQLResponse1(System.Data.DataTable DataTable) {
            this.DataTable = DataTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class genReportAnySQLRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cmdSQL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string sfilename;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string username;
        
        public genReportAnySQLRequest1() {
        }
        
        public genReportAnySQLRequest1(string cmdSQL, string sfilename, string username) {
            this.cmdSQL = cmdSQL;
            this.sfilename = sfilename;
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class genReportAnySQLResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public genReportAnySQLResponse1() {
        }
        
        public genReportAnySQLResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAnySQLTestRequest1 {
        
        public getListAnySQLTestRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListAnySQLTestResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Data.DataTable DataTable;
        
        public getListAnySQLTestResponse1() {
        }
        
        public getListAnySQLTestResponse1(System.Data.DataTable DataTable) {
            this.DataTable = DataTable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_getListRequest1 {
        
        public send_getListRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_getListResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public send_getListResponse1() {
        }
        
        public send_getListResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_getList_newRequest1 {
        
        public send_getList_newRequest1() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class send_getList_newResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://192.168.40.253:81/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string @string;
        
        public send_getList_newResponse1() {
        }
        
        public send_getList_newResponse1(string @string) {
            this.@string = @string;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ServiceHttpPostChannel : DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ServiceHttpPostClient : System.ServiceModel.ClientBase<DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost>, DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost {
        
        public ServiceHttpPostClient() {
        }
        
        public ServiceHttpPostClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHttpPostClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHttpPostClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHttpPostClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.HelloWorldResponse1 DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost.HelloWorld(DermalogMultiScannerDemo.ServiceReference1.HelloWorldRequest1 request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DermalogMultiScannerDemo.ServiceReference1.HelloWorldRequest1 inValue = new DermalogMultiScannerDemo.ServiceReference1.HelloWorldRequest1();
            DermalogMultiScannerDemo.ServiceReference1.HelloWorldResponse1 retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost)(this)).HelloWorld(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Response1 DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost.HelloWorld2(DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Request1 request) {
            return base.Channel.HelloWorld2(request);
        }
        
        public string HelloWorld2() {
            DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Request1 inValue = new DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Request1();
            DermalogMultiScannerDemo.ServiceReference1.HelloWorld2Response1 retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost)(this)).HelloWorld2(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getListResponse1 DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost.getList(DermalogMultiScannerDemo.ServiceReference1.getListRequest1 request) {
            return base.Channel.getList(request);
        }
        
        public string[] getList() {
            DermalogMultiScannerDemo.ServiceReference1.getListRequest1 inValue = new DermalogMultiScannerDemo.ServiceReference1.getListRequest1();
            DermalogMultiScannerDemo.ServiceReference1.getListResponse1 retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost)(this)).getList(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getList2Response1 DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost.getList2(DermalogMultiScannerDemo.ServiceReference1.getList2Request1 request) {
            return base.Channel.getList2(request);
        }
        
        public string[] getList2() {
            DermalogMultiScannerDemo.ServiceReference1.getList2Request1 inValue = new DermalogMultiScannerDemo.ServiceReference1.getList2Request1();
            DermalogMultiScannerDemo.ServiceReference1.getList2Response1 retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost)(this)).getList2(inValue);
            return retVal.ArrayOfString;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getListAllResponse1 DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost.getListAll(DermalogMultiScannerDemo.ServiceReference1.getListAllRequest1 request) {
            return base.Channel.getListAll(request);
        }
        
        public System.Data.DataTable getListAll() {
            DermalogMultiScannerDemo.ServiceReference1.getListAllRequest1 inValue = new DermalogMultiScannerDemo.ServiceReference1.getListAllRequest1();
            DermalogMultiScannerDemo.ServiceReference1.getListAllResponse1 retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost)(this)).getListAll(inValue);
            return retVal.DataTable;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterResponse1 DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost.getListTaxmaster(DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterRequest1 request) {
            return base.Channel.getListTaxmaster(request);
        }
        
        public System.Data.DataTable getListTaxmaster(string cmdSQL) {
            DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterRequest1 inValue = new DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterRequest1();
            inValue.cmdSQL = cmdSQL;
            DermalogMultiScannerDemo.ServiceReference1.getListTaxmasterResponse1 retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost)(this)).getListTaxmaster(inValue);
            return retVal.DataTable;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getListAnySQLResponse1 DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost.getListAnySQL(DermalogMultiScannerDemo.ServiceReference1.getListAnySQLRequest1 request) {
            return base.Channel.getListAnySQL(request);
        }
        
        public System.Data.DataTable getListAnySQL(string cmdSQL) {
            DermalogMultiScannerDemo.ServiceReference1.getListAnySQLRequest1 inValue = new DermalogMultiScannerDemo.ServiceReference1.getListAnySQLRequest1();
            inValue.cmdSQL = cmdSQL;
            DermalogMultiScannerDemo.ServiceReference1.getListAnySQLResponse1 retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost)(this)).getListAnySQL(inValue);
            return retVal.DataTable;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLResponse1 DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost.genReportAnySQL(DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLRequest1 request) {
            return base.Channel.genReportAnySQL(request);
        }
        
        public string genReportAnySQL(string cmdSQL, string sfilename, string username) {
            DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLRequest1 inValue = new DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLRequest1();
            inValue.cmdSQL = cmdSQL;
            inValue.sfilename = sfilename;
            inValue.username = username;
            DermalogMultiScannerDemo.ServiceReference1.genReportAnySQLResponse1 retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost)(this)).genReportAnySQL(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestResponse1 DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost.getListAnySQLTest(DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestRequest1 request) {
            return base.Channel.getListAnySQLTest(request);
        }
        
        public System.Data.DataTable getListAnySQLTest() {
            DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestRequest1 inValue = new DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestRequest1();
            DermalogMultiScannerDemo.ServiceReference1.getListAnySQLTestResponse1 retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost)(this)).getListAnySQLTest(inValue);
            return retVal.DataTable;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.send_getListResponse1 DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost.send_getList(DermalogMultiScannerDemo.ServiceReference1.send_getListRequest1 request) {
            return base.Channel.send_getList(request);
        }
        
        public string send_getList() {
            DermalogMultiScannerDemo.ServiceReference1.send_getListRequest1 inValue = new DermalogMultiScannerDemo.ServiceReference1.send_getListRequest1();
            DermalogMultiScannerDemo.ServiceReference1.send_getListResponse1 retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost)(this)).send_getList(inValue);
            return retVal.@string;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DermalogMultiScannerDemo.ServiceReference1.send_getList_newResponse1 DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost.send_getList_new(DermalogMultiScannerDemo.ServiceReference1.send_getList_newRequest1 request) {
            return base.Channel.send_getList_new(request);
        }
        
        public string send_getList_new() {
            DermalogMultiScannerDemo.ServiceReference1.send_getList_newRequest1 inValue = new DermalogMultiScannerDemo.ServiceReference1.send_getList_newRequest1();
            DermalogMultiScannerDemo.ServiceReference1.send_getList_newResponse1 retVal = ((DermalogMultiScannerDemo.ServiceReference1.ServiceHttpPost)(this)).send_getList_new(inValue);
            return retVal.@string;
        }
    }
}
